# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import wxrpcauth_pb2 as wxrpcauth__pb2


class wxAuthStub(object):
  """The wxAuth service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.checkClientVersion = channel.unary_unary(
        '/wxAuth/checkClientVersion',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )
    self.checkClient2Version = channel.unary_unary(
        '/wxAuth/checkClient2Version',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )
    self.checkServerVersion = channel.unary_unary(
        '/wxAuth/checkServerVersion',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )
    self.wxRPCAuth = channel.unary_unary(
        '/wxAuth/wxRPCAuth',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )
    self.getWxBotKey = channel.unary_unary(
        '/wxAuth/getWxBotKey',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.ByteReplay.FromString,
        )
    self.checkWxBot = channel.unary_unary(
        '/wxAuth/checkWxBot',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )
    self.CallAutoEditor = channel.unary_unary(
        '/wxAuth/CallAutoEditor',
        request_serializer=wxrpcauth__pb2.AuthRequest.SerializeToString,
        response_deserializer=wxrpcauth__pb2.AuthReply.FromString,
        )


class wxAuthServicer(object):
  """The wxAuth service definition.
  """

  def checkClientVersion(self, request, context):
    """wxAuth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkClient2Version(self, request, context):
    """wxAuth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkServerVersion(self, request, context):
    """wxAuth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def wxRPCAuth(self, request, context):
    """wxAuth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getWxBotKey(self, request, context):
    """get wxBot info
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkWxBot(self, request, context):
    """wxBot check
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallAutoEditor(self, request, context):
    """AutoEditor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_wxAuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'checkClientVersion': grpc.unary_unary_rpc_method_handler(
          servicer.checkClientVersion,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
      'checkClient2Version': grpc.unary_unary_rpc_method_handler(
          servicer.checkClient2Version,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
      'checkServerVersion': grpc.unary_unary_rpc_method_handler(
          servicer.checkServerVersion,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
      'wxRPCAuth': grpc.unary_unary_rpc_method_handler(
          servicer.wxRPCAuth,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
      'getWxBotKey': grpc.unary_unary_rpc_method_handler(
          servicer.getWxBotKey,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.ByteReplay.SerializeToString,
      ),
      'checkWxBot': grpc.unary_unary_rpc_method_handler(
          servicer.checkWxBot,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
      'CallAutoEditor': grpc.unary_unary_rpc_method_handler(
          servicer.CallAutoEditor,
          request_deserializer=wxrpcauth__pb2.AuthRequest.FromString,
          response_serializer=wxrpcauth__pb2.AuthReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'wxAuth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
